build(monorepo): Switch to pnpm, use external eslint config & support transpiling monorepo packages

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,9 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-yarn lint-staged
+if [ ! -e "pnpm-lock.yaml" ]; then
+    echo "pnpm-lock.yaml is missing! `pnpm install` and `git commit --ammend` to fix."
+    exit 1
+fi
+
+pnpm lint-staged
