build(husky): Add check for yarn.lock to husky prepush to ensure it exists to avoid breaking CD

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,10 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
+if [ ! -e "yarn.lock" ]; then
+    echo "yarn.lock is missing! `yarn install` and `git commit --ammend` to fix."
+    exit 1
+fi
+
 yarn run type-check
+
